---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-deployment
  template:
    metadata:
      labels:
        app: simple-deployment
    spec:
      containers:
      - name: simple-deployment
        image: 889397717348.dkr.ecr.eu-west-1.amazonaws.com/html-server-image:v1
        ports:
        - containerPort: 80
