apiVersion: v1
kind: Pod
metadata:
  labels:
    run: use-pv
  name: use-pv
spec:
  volumes:
  - name: pv-1-storage
    persistentVolumeClaim:
      claimName: pvc
  containers:
  - image: nginx
    name: use-pv
    volumeMounts:
      - mountPath: "/data"
        name: pv-1-storage
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
