apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-retain
  volumeMode: Filesystem
  volumeName: pv